# fly.toml app configuration file generated for part-2-notes on 2023-07-13T13:26:33-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "part-2-notes"
primary_region = "bos"

[env]
  PORT = "8080" # add this

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
